/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideExternalLink: typeof import('~icons/lucide/external-link')['default']
  const LucidePlay: typeof import('~icons/lucide/play')['default']
  const LucideRotateCw: typeof import('~icons/lucide/rotate-cw')['default']
  const LucideSquare: typeof import('~icons/lucide/square')['default']
}
