"""Tests for AppRepository moving an app between revisions, against real repos."""

from __future__ import annotations

import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

import pilot
from pilot.config import AppConfig
from pilot.core.app import repository
from pilot.core.app.repository import AppRepository
from pilot.core.app.revisions import RevisionPin
from pilot.exceptions import BenchError, CommandError
from pilot.internal.git import GitRepo


def _git(path: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(path), *args], check=True, capture_output=True)


def _repo_with_two_commits(path: Path) -> tuple[Path, str]:
    """A repo on `main` with two commits, and the sha of the first."""
    path.mkdir(parents=True)
    subprocess.run(["git", "init", "-q", "-b", "main", str(path)], check=True)
    _git(path, "config", "user.email", "t@t.com")
    _git(path, "config", "user.name", "t")
    (path / "file").write_text("first")
    _git(path, "add", "file")
    _git(path, "commit", "-q", "-m", "first")
    (path / "file").write_text("second")
    _git(path, "commit", "-qam", "second")
    return path, GitRepo(path).head_sha


class _FakeApp:
    def __init__(self, path: Path) -> None:
        self.path = path
        self.config = AppConfig(name="demo", repo="", branch="main")
        self.bench = SimpleNamespace(path=path.parent)


def _repository(path: Path) -> AppRepository:
    return AppRepository(_FakeApp(path))


def test_checkout_moves_revision_when_a_build_dirtied_the_repo(tmp_path: Path) -> None:
    """Building an app's assets writes generated files back into its own repo, so
    the update after a build meets a dirty tree and git refuses to check out."""
    path, _ = _repo_with_two_commits(tmp_path / "app")
    first = GitRepo(path)._run("rev-parse", "HEAD~1").stdout.strip()
    (path / "file").write_text("regenerated by the asset build")

    _repository(path)._checkout_pinned_ref(first)

    assert GitRepo(path).head_sha == first
    assert (path / "file").read_text() == "first"


def test_checkout_keeps_the_dirty_work_in_the_stash(tmp_path: Path) -> None:
    """The revision moved to may conflict with it, so it is kept rather than
    reapplied - but never dropped, since some of it is the user's own edit."""
    path, _ = _repo_with_two_commits(tmp_path / "app")
    first = GitRepo(path)._run("rev-parse", "HEAD~1").stdout.strip()
    (path / "file").write_text("a local edit worth keeping")

    _repository(path)._checkout_pinned_ref(first)

    assert "stash@{0}" in GitRepo(path)._run("stash", "list").stdout


def test_checkout_of_a_clean_repo_stashes_nothing(tmp_path: Path) -> None:
    path, _ = _repo_with_two_commits(tmp_path / "app")
    first = GitRepo(path)._run("rev-parse", "HEAD~1").stdout.strip()

    _repository(path)._checkout_pinned_ref(first)

    assert GitRepo(path)._run("stash", "list").stdout.strip() == ""


@pytest.fixture
def git_calls(monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
    """Records the git command lines AppRepository would have run."""
    calls: list[list[str]] = []
    monkeypatch.setattr(repository, "run_command", lambda cmd, **kwargs: calls.append(cmd))
    monkeypatch.setattr(AppRepository, "remote_url", property(lambda self: "https://host/demo.git"))
    monkeypatch.setattr(AppRepository, "_sync_remote_url", lambda self: None)
    return calls


def _set_dev_install(monkeypatch: pytest.MonkeyPatch, dev: bool) -> None:
    monkeypatch.setattr(pilot, "is_dev_build", dev)


def test_release_install_clones_shallow(
    tmp_path: Path, git_calls: list[list[str]], monkeypatch: pytest.MonkeyPatch
) -> None:
    _set_dev_install(monkeypatch, False)

    _repository(tmp_path / "app").clone()

    assert git_calls[0][-3:-1] == ["--depth", "1"]


def test_dev_install_clones_the_full_history(
    tmp_path: Path, git_calls: list[list[str]], monkeypatch: pytest.MonkeyPatch
) -> None:
    _set_dev_install(monkeypatch, True)

    _repository(tmp_path / "app").clone()

    assert "--depth" not in git_calls[0]


def test_dev_install_does_not_shallow_a_pinned_checkout(
    tmp_path: Path, git_calls: list[list[str]], monkeypatch: pytest.MonkeyPatch
) -> None:
    """`fetch --depth 1` would truncate a full clone, so a dev install skips it."""
    _set_dev_install(monkeypatch, True)
    monkeypatch.setattr(AppRepository, "_checkout_pinned_ref", lambda self, ref: None)

    _repository(tmp_path / "app").checkout_pinned_target(RevisionPin(kind="tag", ref="v1.0.0"))

    assert "--depth" not in git_calls[0]


def test_update_leaves_an_inherited_shallow_repo_shallow(
    tmp_path: Path, git_calls: list[list[str]], monkeypatch: pytest.MonkeyPatch
) -> None:
    """An app cloned before the dev install is not backfilled - that would drag down
    the full history of every app on the next update."""
    _set_dev_install(monkeypatch, True)
    monkeypatch.setattr(AppRepository, "is_shallow", property(lambda self: True))

    _repository(tmp_path / "app").update()

    assert git_calls[0][-1] == "--depth=1"


def test_update_of_a_full_repo_passes_no_depth(
    tmp_path: Path, git_calls: list[list[str]], monkeypatch: pytest.MonkeyPatch
) -> None:
    _set_dev_install(monkeypatch, True)
    monkeypatch.setattr(AppRepository, "is_shallow", property(lambda self: False))

    _repository(tmp_path / "app").update()

    assert "--depth=1" not in git_calls[0]


def test_pinned_tag_fetch_passes_git_auth_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls: list[tuple[list[str], dict]] = []

    def record(cmd, **kwargs):
        calls.append((cmd, kwargs))

    repo = _repository(tmp_path / "app")
    monkeypatch.setattr(repository, "run_command", record)
    monkeypatch.setattr(AppRepository, "_sync_remote_url", lambda self: None)
    monkeypatch.setattr(AppRepository, "git_env", property(lambda self: {"GIT_CONFIG_COUNT": "1"}))
    monkeypatch.setattr(AppRepository, "_checkout_pinned_ref", lambda self, ref: None)
    monkeypatch.setattr(AppRepository, "is_shallow", property(lambda self: False))

    repo.checkout_pinned_target(RevisionPin(kind="tag", ref="v1.2.3"))

    assert calls[0][0][-3:] == ["fetch", "origin", "v1.2.3"]
    assert calls[0][1]["env"] == {"GIT_CONFIG_COUNT": "1"}


def test_pinned_commit_fetch_passes_git_auth_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls: list[tuple[list[str], dict]] = []

    def record(cmd, **kwargs):
        calls.append((cmd, kwargs))

    repo = _repository(tmp_path / "app")
    monkeypatch.setattr(repository, "run_command", record)
    monkeypatch.setattr(AppRepository, "_sync_remote_url", lambda self: None)
    monkeypatch.setattr(AppRepository, "git_env", property(lambda self: {"GIT_CONFIG_COUNT": "1"}))
    monkeypatch.setattr(AppRepository, "_checkout_pinned_ref", lambda self, ref: None)
    monkeypatch.setattr(AppRepository, "is_shallow", property(lambda self: False))

    repo.checkout_pinned_commit("abc1234")

    assert calls[0][0][-3:] == ["fetch", "origin", "abc1234"]
    assert calls[0][1]["env"] == {"GIT_CONFIG_COUNT": "1"}


def test_pinned_commit_fallback_fetch_passes_git_auth_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    calls: list[tuple[list[str], dict]] = []
    attempt = {"n": 0}

    def record(cmd, **kwargs):
        calls.append((cmd, kwargs))
        if "fetch" in cmd and attempt["n"] == 0:
            attempt["n"] += 1
            raise CommandError("initial fetch failed")

    repo = _repository(tmp_path / "app")
    monkeypatch.setattr(repository, "run_command", record)
    monkeypatch.setattr(AppRepository, "_sync_remote_url", lambda self: None)
    monkeypatch.setattr(AppRepository, "git_env", property(lambda self: {"GIT_CONFIG_COUNT": "1"}))
    monkeypatch.setattr(AppRepository, "_checkout_pinned_ref", lambda self, ref: None)
    monkeypatch.setattr(AppRepository, "is_shallow", property(lambda self: False))

    repo.checkout_pinned_commit("abc1234")

    fetch_calls = [(cmd, kwargs) for cmd, kwargs in calls if "fetch" in cmd]
    assert len(fetch_calls) == 2
    assert fetch_calls[1][0][-3:] == ["fetch", "origin", "main"]
    assert fetch_calls[1][1]["env"] == {"GIT_CONFIG_COUNT": "1"}


def _repository_of(remote: Path, path: Path) -> AppRepository:
    """A repository cloning from `remote` over file://, which honours --depth as a network remote does."""
    app = _FakeApp(path)
    app.config.repo = remote.as_uri()
    return AppRepository(app)


def test_release_install_clones_a_full_commit_without_its_history(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A full clone of a large app like erpnext does not finish."""
    _set_dev_install(monkeypatch, False)
    remote, _ = _repo_with_two_commits(tmp_path / "remote")
    first = GitRepo(remote)._run("rev-parse", "HEAD~1").stdout.strip()

    _repository_of(remote, tmp_path / "app").clone_rev(first)

    clone = GitRepo(tmp_path / "app")
    assert clone.head_sha == first
    assert clone.is_shallow


def test_a_short_commit_is_found_in_the_full_history(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _set_dev_install(monkeypatch, False)
    remote, _ = _repo_with_two_commits(tmp_path / "remote")
    first = GitRepo(remote)._run("rev-parse", "HEAD~1").stdout.strip()

    _repository_of(remote, tmp_path / "app").clone_rev(first[:7])

    assert GitRepo(tmp_path / "app").head_sha == first


def test_a_commit_the_server_will_not_fetch_by_sha_comes_from_the_full_history(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Some servers only serve a commit through a ref, and refuse it asked for by its SHA."""
    _set_dev_install(monkeypatch, False)
    remote, _ = _repo_with_two_commits(tmp_path / "remote")
    first = GitRepo(remote)._run("rev-parse", "HEAD~1").stdout.strip()
    def refuse(self: AppRepository, commit: str) -> None:
        subprocess.run(["git", "init", "-q", str(self.app.path)], check=True)
        raise CommandError("fatal: remote error: upload-pack: not our ref")

    monkeypatch.setattr(AppRepository, "fetch_commit", refuse)

    _repository_of(remote, tmp_path / "app").clone_rev(first)

    clone = GitRepo(tmp_path / "app")
    assert clone.head_sha == first
    assert not clone.is_shallow


def test_a_missing_commit_leaves_no_clone_behind(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A clone left in apps/ would read as an installed app."""
    _set_dev_install(monkeypatch, False)
    remote, _ = _repo_with_two_commits(tmp_path / "remote")

    with pytest.raises(BenchError, match="not found"):
        _repository_of(remote, tmp_path / "app").clone_rev("0" * 40)

    assert not (tmp_path / "app").exists()


def test_files_already_at_the_app_path_are_kept(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The clone did not create them, so a failed clone must not delete them."""
    _set_dev_install(monkeypatch, False)
    remote, _ = _repo_with_two_commits(tmp_path / "remote")
    (tmp_path / "app").mkdir()
    (tmp_path / "app" / "notes").write_text("not ours")

    with pytest.raises(CommandError):
        _repository_of(remote, tmp_path / "app").clone_rev("0" * 40)

    assert (tmp_path / "app" / "notes").read_text() == "not ours"
