#!/usr/bin/env python3
"""Generate TypeScript interfaces from backend response dataclasses. Run with:
    uv run python scripts/generate_ts_types.py
"""

from __future__ import annotations

import types
from dataclasses import fields, is_dataclass
from pathlib import Path
from typing import Union, get_args, get_origin, get_type_hints

from admin.backend.providers.storage import StorageBreakdown
from pilot.core.bench.audit_log import AuditEntry
from pilot.core.notification import Notification
from pilot.core.site.storage import SiteStorageReport

_TARGETS = (
    ((StorageBreakdown,), "admin/frontend/dashboard/src/types/storage.ts"),
    ((SiteStorageReport,), "admin/frontend/dashboard/src/types/siteStorage.ts"),
    ((AuditEntry,), "admin/frontend/dashboard/src/types/audit.ts"),
    ((Notification,), "admin/frontend/dashboard/src/types/notification.ts"),
)
_PRIMITIVES = {str: "string", int: "number", float: "number", bool: "boolean"}


def _is_union(tp) -> bool:
    return isinstance(tp, types.UnionType) or get_origin(tp) is Union


def _ts_type(tp) -> str:
    if _is_union(tp):
        args = get_args(tp)
        parts = [_ts_type(a) for a in args if a is not type(None)]
        if type(None) in args:
            parts.append("null")
        return " | ".join(parts)
    if get_origin(tp) is list:
        (item,) = get_args(tp)
        return f"{_ts_type(item)}[]"
    if is_dataclass(tp):
        return tp.__name__
    return _PRIMITIVES.get(tp, "any")


def _nested_dataclasses(tp):
    if _is_union(tp):
        for arg in get_args(tp):
            yield from _nested_dataclasses(arg)
    elif get_origin(tp) is list:
        (item,) = get_args(tp)
        yield from _nested_dataclasses(item)
    elif is_dataclass(tp):
        yield tp


def _collect(dc, seen: set, order: list) -> None:
    if dc in seen:
        return
    seen.add(dc)
    hints = get_type_hints(dc)
    for f in fields(dc):
        for nested in _nested_dataclasses(hints[f.name]):
            _collect(nested, seen, order)
    order.append(dc)


def _render(dc) -> str:
    hints = get_type_hints(dc)
    lines = [f"export interface {dc.__name__} {{"]
    for f in fields(dc):
        lines.append(f"  {f.name}: {_ts_type(hints[f.name])}")
    lines.append("}")
    return "\n".join(lines)


def generate(roots) -> str:
    seen: set = set()
    order: list = []
    for root in roots:
        _collect(root, seen, order)
    header = "// AUTO-GENERATED by scripts/generate_ts_types.py - do not edit by hand.\n"
    return header + "\n" + "\n\n".join(_render(dc) for dc in order) + "\n"


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    for roots, out_path in _TARGETS:
        full_path = repo_root / out_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(generate(roots))
        print(f"wrote {full_path}")


if __name__ == "__main__":
    main()
